### ISSUE TITLE
Multiple ads on a Page

### ISSUE THREAD

**Issue by RussStringham** [WICG/privacy-preserving-ads#1]
Most pages display multiple ads. When the ad network cannot tell who the ad is being shown to, but only knows cohorts/interests/context, it is likely that the same ad (or ads from the same advertiser campaign) may win the bids for multiple ad locations on that page. This could be a real problem; it is more than simple frequency capping.

With PARAKEET, the page could request all ads in a single request, such that the ad network can coordinate the set of ads returned. The request should indicate ads that will be immediately visible (above the fold) and those that will only be visible if the user scrolls. 

The main issue might be that even with some reasonable limit on the number of ads requested, it might make it easier to communicate some type of user ID within the metadata of the request. PARAKEET might address this by sometimes splitting this up into multiple requests to the ad network (but still more than a single ad per request) and then eliminating any duplicate ads.

While this issue applies to TURTLEDOVE, SPARROW, etc. as well, I think PARAKEET is better positioned to provide a good solution.

**Comment by mehulparsana** [comment]
We're open to exploring requesting multiple ads in a single request, perhaps with params indicating number of ads, size, location, etc., with protections against that information becoming individually identifiable. 

However, if there are multiple requests initiated for same page, keeping linkage between consecutive requests will be difficult. These requests should interpreted independently.
