### ISSUE TITLE
Scheduled calls for PARAKEET

### ISSUE THREAD

**Issue by KeldaAnders** [WICG/privacy-preserving-ads#3]
As a follow-up to sharing our PARAKEET proposal, we had scheduled biweekly discussions to encourage open discussion, review technical details and resolve open issues. 

### Meetings are currently paused

We are continuing to iterate on an updated proposal. We'll resume meetings when we're able to share something substantial.

If you want to participate, please make sure you join the WICG: https://www.w3.org/community/wicg/

New call-in info will be made available when calls resume.

**[Meeting Agenda, Notes, and Attendance will be recorded here](https://docs.google.com/document/d/1AisedrNyJRDxvehaSactuS6zrLy4htDaRyiZDcyktqE/edit?usp=sharing)**

#### Previous Discussion Details:

- [2021-03-15 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-03-15.md)
- [2021-04-07 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-04-07.md)
   - [2021-04-07 Presentation](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/Parakeet%20High%20Level%20Onboarding-2021-04-07.pdf)
 - [2021-04-21 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-04-21.md)
- [2021-05-05 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-05-05.md)
- [2021-05-25 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-05-25.md)
   - [2021-05-25 Presentation](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/PARAKEET-Polyfill-V0-Testing.pdf)
- [2021-06-02 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-06-02.md)
- [2021-06-16 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-06-16.md)
- [2021-06-30 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-06-30.md)
    - [PARAKEET-Polyfill-Test Setup](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/PARAKEET-Polyfill-Test%20Setup.pdf)
- [2021-07-14 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-07-14.md)
- [2021-08-11 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-08-11.md)
    -  [PARAKEET Client-Side Decision Logic](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/PARAKEET_Client-Side_Decision_Logic.pdf) (A steppingstone towards MACAW functionality)
    
- [2021-08-25 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-08-25.md)
   -  [PARAKEET Polyfill Sign-up](https://github.com/microsoft/PARAKEET/issues/7)
 - [2021-09-08 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-09-08.md)
 - [2021-09-22 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-09-22.md)
 - [2021-10-06 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-10-06.md)
 -  [2021-11-03 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2021-11-03.md)
 -  [2022-01-12 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2022-01-22.md)
 -  [2022-02-09 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2022-02-09.md)
 - [2022-05-04 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2022-05-04.md)
 - [2022-05-18 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2022-05-18.md)
 - [2022-06-15 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2022-06-15.md)
 - [2022-08-24 Meeting Notes](https://github.com/WICG/privacy-preserving-ads/blob/main/PARAKEET-OpenDiscussion/2022-08-24.md)

**Comment by brodrigu** [comment]
Magnite would be interested in participating in PARAKEET discussions.

**Comment by peligio** [comment]
Interested in this continuing. Please publicise the call cadence in advance to improve attendance/participation from the broader industry.

**Comment by KeldaAnders** [comment]
Thank you @peligio I will make sure to more clearly announcing our future PARAKEET discussions. We will continue to host this call on a Bi-weekly cadence (Wednesdays,  at 5 pm CEST / 11 am EDT / 8 am PDT).

I will also keep posting the meeting notes on this issue to keep everyone up to date on what we'veve discussed.

**Comment by KeldaAnders** [comment]
**Our Agenda for Wednesday, May 5th at 5 pm CEST / 11 am EDT / 8 am PDT Discussion is:**

- https://github.com/WICG/privacy-preserving-ads/issues/17
- https://github.com/WICG/privacy-preserving-ads/issues/18
- https://github.com/WICG/privacy-preserving-ads/issues/19

**Comment by brodrigu** [comment]
@KeldaAnders can we get an update on OpenRTB support in Parakeet to this weeks call? https://github.com/WICG/privacy-preserving-ads/issues/37

**Comment by KeldaAnders** [comment]
Thanks, @brodrigu,
We've added it to the agenda for tomorrow's sync: https://github.com/WICG/privacy-preserving-ads/issues/3

**Comment by bm371613** [comment]
Could we have the discussion about #47 on 2022-08-24? I wanted to bring this issue up today, the meeting has been postponed to 2022-08-10, but I cannot attend at that day.

**Comment by KeldaAnders** [comment]
@bm371613 Thank you for flagging this, we have rescheduled the [#47](https://github.com/WICG/privacy-preserving-ads/issues/47) discussion to be Wednesday, August 24th

**Comment by erik-anderson** [comment]
Hi everyone, Kelda's out this week, so I'm posting an update as a comment instead. We do not have an agenda for the January 11th meeting and are cancelling that upcoming instance.

**Comment by Brandr0id** [comment]
Resolving in favour of tracking Ad Selection API calls in #50
