### ISSUE TITLE
Call to discuss MPC and measurement

### ISSUE THREAD

**Issue by erik-anderson** [WICG/privacy-preserving-ads#39]
Per the discussion in this issue, we had a one-off call:

- Date and time: **Monday, November 8th at 9am PT/12pm ET**.
- [Minutes](https://github.com/WICG/privacy-preserving-ads/blob/main/meetings/2021-11-08-minutes-mpc-measurement.md)

---

There's a lot of activity happening across various entities that are working to propose novel solutions to use multi-party computation to help solve measurement use cases in a privacy-preserving way:

* [Attribution Reporting API with Aggregate Reports](https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md) uses a DPF-based approach with two helper services.
* [Secure Multi-Party Aggregation using oblivious bucketization](https://github.com/WICG/privacy-preserving-ads/blob/main/Bucketization.md) leverages three helper services.
* [ISRG's Privacy Preserving Measurement Protocol](https://github.com/abetterinternet/ppm-specification)
* ...and likely others

There are higher-level questions across all of these that we'd ideally have a forum on discussing how different folks want to do evaluations and comparisons, explore more collaboration opportunities, discuss higher-level policy and threat model questions, etc.

There's already the every-other-week [Attribution Reporting API meeting](https://github.com/WICG/conversion-measurement-api/issues/80) which likely has many of the right participants, but that meeting naturally gravitates toward discussing the specific proposals in that repo and implementation status; it's difficult to structure and have some of the broader coordination on MPC proposals.

Given TPAC is ongoing, I'd propose that we start the week of November 1st or later. Given participant overlap, it may make sense to slot this in opposite the existing Attribution Reporting API meeting.

If you are interested in participating in this, please comment on this issue and state if every other Monday at 9am PT/12pm ET will generally work for you. If we get consensus on that time, then I'd like to have our first meeting November 8th.

If you'd like to propose an alternate set of possible times, we can evaluate that too.

**Comment by eriktaubeneck** [comment]
+1 would love to participate. Happy to get up early in Pacific time to help accommodate our APAC friends. 

I'm particularly interested in making progress in how MPC can work across the board, both in terms of who needs to be trusted for what, and how to handle the cost of MPC between the involved parties.

**Comment by schoppmp** [comment]
+1 this sounds like a great idea, happy to join! The proposed time (Mondays 12pm ET) works for me.

**Comment by erik-anderson** [comment]
I've edited the first comment on this issue with meeting logistics. Please update your calendar items.

I've proposed a tentative agenda in the agenda and minutes doc; if you'd like to see changes please edit and/or add comments to the doc directly.

To reiterate the above, ideally we'll get the W3C portions of this conversation moved to the PATCG as is being discussed in their [meetings issue #4](https://github.com/patcg/meetings/issues/4).

**Comment by erik-anderson** [comment]
Thanks to everyone that attended! I thought it was a good conversation.

For folks who were unable to make it, I've converted the [minutes](https://github.com/WICG/privacy-preserving-ads/blob/main/meetings/2021-11-08-minutes-mpc-measurement.md) to markdown and checked them into this repo.

My high-level takeaways were:
1. Various IETF groups are proceeding with specifying in more detail approaches based on existing crypto primitives. Folks with potential feedback on a charter for a group putting together a higher-level aggregate measurement protocol should consider attending the IETF BOF happening for it on Nov. 10th.
2. The W3C Private Ad Tech CG (PAT CG) is similarly getting up and running and will discuss measurement-related proposals there.
3. Effective layering the conversations and the standardization is important. Many topics may span across them, though, so at times it can be ambiguous where to start. We should work to have clear locations for folks to pose important topics for discussion.
4. Once we have super clear use cases that may require protocol changes, we'll want to go back to IETF and the IRTF/CFRG only after we have completed due diligence (to be respectful of that group's time and energy).

It isn't clear that PAT CG will be the right place for some of this conversation, but there was also not a lot of clarity if there's _any_ current, good location for some of the conversations.

My proposed next step is to work with the PAT CG to get "measurement" adopted as a broad work item and make sure we have a location in a generally agreed upon GitHub repo to host the discussions folks want to have around aggregate measurement protocols and crypto. If we get consensus that some topics are already best covered elsewhere, e.g. an IETF group, we should work to give folks the right pointers. To be determined if/how we spin up breakout sessions for a core set of participants for a set of topics.

Feedback welcome on next steps.

**Comment by npdoty** [comment]
Sorry that I missed this meeting. 

Opening an issue on a github repo isn't a good way to schedule a meeting that might be of broader interest to multiple groups.

**Comment by erik-anderson** [comment]
> Sorry that I missed this meeting.
> 
> Opening an issue on a github repo isn't a good way to schedule a meeting that might be of broader interest to multiple groups.

Thanks for the feedback. I'm sorry I didn't advertise it broadly enough to reach you. This is exactly why I'd like to get this topic moved into the PAT CG (and other applicable groups) moving forward.

**Comment by eriktaubeneck** [comment]
@erik-anderson thanks for sharing the minutes, and I apologize that I was unable to attend due to a scheduling conflict on my end. Just wanted to drop in and add my support for your proposed next step with the PATCG, and I plan to attend future sessions on this work in whatever format emerges.

**Comment by marianapr** [comment]
I think aiming to move this discussion into PAT CG makes sense. I also do strongly feel that we need a dedicated stream that will go in depth in the MPC solutions which is separate from high level discussions about functionality. And this discussion should be happening before bringing it to IETF in order to be able to iterate and be more flexible.

**Comment by erik-anderson** [comment]
We'll discuss this more in this week's PAT CG meeting: https://github.com/patcg/meetings/issues/9.
