### ISSUE TITLE
Reference to Parakeet as a previous proposal, probably a typo

### ISSUE THREAD

**Issue by johnwilander** [WICG/privacy-preserving-ads#8]
> The key difference between previously proposed approaches such as TURTLEDOVE and PARAKEET is multiple ad requests with segregated information vs. a combined anonymized ad request.

Is PARAKEET supposed to be FLEDGE or SPARROW in the above sentence?

**Comment by erik-anderson** [comment]
I don't believe so, but I agree this reads awkwardly.
